server:
  port: 8010
# 后台访问路径  http://localhost:8010/admin/admin/index
# 前台访问路径  http://localhost:8010/static/index.html  110  110
spring:
  # 以下配置能使用elasticsearchTemplate
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spark_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456
  resources:
    add-mappings: true #如果所有所有controller没用命中，匹配静态资源
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#admin官方账号的用户名以及密码
admin:
  email: admin@qq.com
  password: e10adc3949ba59abbe56e057f20f883e
#声明es服务
elasticsearch:
  ip: 127.0.0.1:9200
